### ISSUE TITLE
typed ActorSystem を new して使うと一部モジュールでエラー

### ISSUE THREAD

**Issue by tksugimoto** [lerna-stack/lerna-app-library#24]
`java.lang.UnsupportedOperationException: cannot create top-level actor from the outside on ActorSystem with custom user guardian`

[Feature/akka typed by tksugimoto · Pull Request #22 · lerna-stack/lerna-sample-payment-app](https://github.com/lerna-stack/lerna-sample-payment-app/pull/22/checks?check_run_id=2772435825#step:9:1221)

> [info]           java.lang.UnsupportedOperationException: cannot create top-level actor from the outside on ActorSystem with custom user guardian  
> 1222  
> [info]           at akka.actor.ActorSystemImpl.actorOf(ActorSystem.scala:901)  
> 1223  
> [info]           at lerna.util.akka.AtLeastOnceDelivery$.tellTo(AtLeastOnceDelivery.scala:120)  
> 1224  
> [info]           at jp.co.tis.lerna.payment.application.ecpayment.issuing.actor.PaymentActorSpec.$anonfun$new$18(PaymentActorSpec.scala:232)  

## 問題の場所
[lerna-app-library/AtLeastOnceDelivery.scala at 92f060be39128675ae9c26fea80ab6f423c1050d · lerna-stack/lerna-app-library](https://github.com/lerna-stack/lerna-app-library/blob/92f060be39128675ae9c26fea80ab6f423c1050d/lerna-util-akka/src/main/scala/lerna/util/akka/AtLeastOnceDelivery.scala#L120)

>     val atLeastOnceDeliveryProxy = system.toClassic.actorOf(AtLeastOnceDelivery.props(destination.toClassic))  

## 発生すると思われるコード

```
$ git grep system.*.actorOf */src/main
lerna-management/src/main/scala/lerna/management/stats/MetricsImpl.scala:  private val actor: ActorRef            = system.actorOf(MetricsActor.props())
lerna-util-akka/src/main/scala/lerna/util/akka/AtLeastOnceDelivery.scala:    val atLeastOnceDeliveryProxy = system.actorOf(AtLeastOnceDelivery.props(destination))
lerna-util-akka/src/main/scala/lerna/util/akka/AtLeastOnceDelivery.scala:    val atLeastOnceDeliveryProxy = system.actorOf(AtLeastOnceDelivery.props(destination))
lerna-util-akka/src/main/scala/lerna/util/akka/AtLeastOnceDelivery.scala:    val atLeastOnceDeliveryProxy = system.toClassic.actorOf(AtLeastOnceDelivery.props(destination.toClassic)).toTyped
lerna-util-akka/src/main/scala/lerna/util/akka/AtLeastOnceDelivery.scala:    val atLeastOnceDeliveryProxy = system.toClassic.actorOf(AtLeastOnceDelivery.props(destination.toClassic))
lerna-util-sequence/src/main/scala/lerna/util/sequence/CassandraSequenceFactory.scala:    val actor = system.actorOf(
```

## 原因
[akka/akka - Gitter](https://gitter.im/akka/akka?at=5dd30275ca778c1fbf291e00)

> if you need system.toClassic.actorOf you have to start it as akka.actor.ActorSystem, which you can adapt with .toTyped

`typedSystem.toClassic.actorOf `  が使えるのは元々クラシックActorSystem の場合のみ。

## 対策
- クラシック Props を typed API (Behavior) に書き換える
  - クラシック `akka.actor.ActorSystem` から Behavior で Actor を作ることは `akka.actor.typed.scaladsl.adapter` を使い `system.toTyped.systemActorOf` を使うことで可能
- (クラシック) Extension 化する
[Classic Akka Extensions • Akka Documentation](https://doc.akka.io/docs/akka/current/extending-akka.html)
  - ExtendedActorSystem が提供され、`def systemActorOf(props: Props, name: String): ActorRef` が使える
    - ※ [typed Extension](https://doc.akka.io/docs/akka/current/typed/extending.html) を使うと、 `ActorSystem[_]` しか得られず、クラシックな `Props` から actor を作れず、 typed 化 or 一層挟む必要がある
    - 参考: [🐞fix: Make classic ClusterReplication an ActorSystem extension · lerna-stack/akka-entity-replication@0a5990a](https://github.com/lerna-stack/akka-entity-replication/commit/0a5990a04076a83c701c9bb103a1d7e4cf47d9a0)

## 関連
- https://github.com/lerna-stack/lerna-app-library/issues/11 ```v2.0.0 · Issue #11 · lerna-stack/lerna-app-library```
  - https://github.com/lerna-stack/lerna-app-library/pull/7 ```Typed/lerna util akka by tksugimoto · Pull Request #7 · lerna-stack/lerna-app-library```
- https://github.com/lerna-stack/lerna-sample-payment-app/pull/22#discussion_r647292978 ```Feature/akka typed by tksugimoto · Pull Request #22 · lerna-stack/lerna-sample-payment-app```
- https://github.com/lerna-stack/lerna-sample-payment-app/pull/30 ```Feature/akka typed actor system by tksugimoto · Pull Request #30 · lerna-stack/lerna-sample-payment-app```

**Comment by tksugimoto** [comment]
https://github.com/lerna-stack/lerna-sample-payment-app/pull/30 でも問題なければ close

**Comment by tksugimoto** [comment]
>lerna-sample-payment-app でも問題なければ close

問題なしだった
