### ISSUE TITLE
[lerna-util-sequence] maxSequence が Int の最大値よりもかなり大きいとき採番に失敗することがある

### ISSUE THREAD

**Issue by negokaz** [lerna-stack/lerna-app-library#88]
## 対象バージョン

`v3.0.1`

## 期待する振る舞い

maxSequence  が大きな数であったとしても、エラーログが出力されず、かつ採番に失敗しない

## 実際の振る舞い

maxSequence  が大きな数の場合以下のようなエラーが出て採番に失敗することがある。

- **採番が高々１並列で、1秒以上の間隔を置いて行われる場合：**
  - ⇒ エラーが出ても採番は成功する
- **並列かあるいは短期間で複数の採番が要求される場合：**
  - ⇒ （タイミングにより）採番が失敗することがある

```
10:26:08.064    ERROR   lerna.util.sequence.SequenceFactoryWorker$      -       -       dummy freeAmount (-1530494984) must be greater than 0 because freeAmount ≦ 0 means that the next sequence is overflowjava.lang.IllegalStateException: freeAmount (-1530494984) must be greater than 0 because freeAmount ≦ 0 means that the next sequence is overflow
        at lerna.util.sequence.SequenceFactoryWorker.prepareNextSequence(SequenceFactoryWorker.scala:226)
        at lerna.util.sequence.SequenceFactoryWorker.acceptGenerateSequence(SequenceFactoryWorker.scala:210)
        at lerna.util.sequence.SequenceFactoryWorker.$anonfun$ready$1(SequenceFactoryWorker.scala:171)
        at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:152)
        at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
        at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
        at akka.actor.typed.internal.InterceptorImpl$$anon$2.apply(InterceptorImpl.scala:57)
        at akka.actor.typed.internal.RestartSupervisor.aroundReceive(Supervision.scala:263)
        at akka.actor.typed.internal.InterceptorImpl.receive(InterceptorImpl.scala:85)
        at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
        at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
        at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:129)
        at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:106)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
        at akka.actor.ActorCell.invoke(ActorCell.scala:547)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

## エラーが出る maxSequence の条件

(`SequenceFactory.maxSequence` - `予約済みの最大値`) / `lerna.util.sequence.max-node-id` が Int の最大値 `2,147,483,647` を超える場合にエラーになる

## 原因

`freeAmount`（追加で予約できる採番値の数）の計算結果が Int の桁あふれによりマイナス値になり、不正な状態を検知するためのアサーションによりエラーになる。

**`freeAmount` の計算ロジック：**
https://github.com/lerna-stack/lerna-app-library/blob/796a5054116ac3c41013cb0fa3cd9f699af60212/lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala#L85-L91

**アサーションの実装箇所：**
https://github.com/lerna-stack/lerna-app-library/blob/796a5054116ac3c41013cb0fa3cd9f699af60212/lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala#L218-L228

**`toInt` で桁あふれし、マイナス値になる例：**
![image](https://github.com/lerna-stack/lerna-app-library/assets/1239141/959dd866-6635-44d1-ae79-b56afd0c0d53)

エラーが出ても採番に成功するケースがあるのは、採番を終えた後に次の採番値を準備しておく処理の中でエラーが出るため。

他に保留（`stash`）されている採番要求がない場合は採番が成功するが、短期間で複数の採番要求が到来して採番要求が保留（`stash`）された場合、エラーが出たタイミングで `SequenceFactoryWorker` が再起動し、`stash` されたメッセージが破棄されるため、このケースでは後続の採番がエラーになる。

## 再現方法

`CassandraSequenceFactorySpec` に以下のようなテストを実装すると、エラーが再現できます。

```scala
"maxSequence が大きいときにエラーが発生しない" in {
      import scala.concurrent.duration._

      implicit val config: Config = baseConfig

      val sequenceFactory: SequenceFactory =
        new TestSequenceFactory(
          seqId = UUID.randomUUID().toString,
          maxSequence = BigInt("99999999999"),
          sequenceCacheSize = 8,
        )
      val sequence = {
        // 1秒おきに採番
        Future.traverse((1 to 10).toList) { t =>
          akka.pattern.after(1.second * t)(sequenceFactory.nextId())
        }
      }
      whenReady(sequence, timeout(11.seconds)) { sequence =>
        val expected = List(
          BigInt(1),
          BigInt(10),
          BigInt(19),
          BigInt(28),
          BigInt(37),
          BigInt(46),
          BigInt(55),
          BigInt(64),
          BigInt(73),
          BigInt(82),
        )
        expect(sequence === expected)
      }
    }
```

## 解決案

`BigInt#toInt` を使わない実装に変更する。
そのためには `Math.min` の代替となるプログラムを実装する必要がある。

**Comment by ydash** [comment]
その他オーバーフローが発生する可能性のある場所がないか確認する

`git grep`でInt型やLong型を用いている箇所のあたりをつける

```
$ git grep -n -E '\s(Int|Long)[), ]' lerna-util-sequence/src/main/scala/lerna/util/sequence/
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryConfig.scala:18:  val nodeId: Int = {
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryConfig.scala:24:  val firstValue: Int = nodeId
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryConfig.scala:26:  val maxNodeId: Int = {
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryConfig.scala:32:  val incrementStep: Int = maxNodeId
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactorySupervisor.scala:10:  def apply(sequenceId: String, maxSequenceValue: BigInt, reservationAmount: Int)(implicit
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactorySupervisor.scala:28:    reservationAmount: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:17:      incrementStep: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:18:      reservationAmount: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:58:      incrementStep: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:59:      reservationAmount: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:60:      reservationFactor: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:110:    incrementStep: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceFactoryWorker.scala:111:    reservationAmount: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceStore.scala:22:  def apply(sequenceId: String, nodeId: Int, incrementStep: BigInt, config: SequenceFactoryCassandraConfig)(implicit
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceStore.scala:158:      reservationAmount: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceStore.scala:174:      reservationAmount: Int,
lerna-util-sequence/src/main/scala/lerna/util/sequence/SequenceStore.scala:216:    nodeId: Int,
```
